# Generated by Django 5.0.6 on 2024-06-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_reviews_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='stars',
        ),
    ]
